FROM python:3.11-slim

WORKDIR /app

# Copiar requirements e instalar dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código da aplicação
COPY . .

EXPOSE 8000

CMD ["uvicorn", "server:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
