name: Close Parent Issue Automatically
on:
  issues:
    types: [closed]

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: Autoclose Parent Issue
        uses: pandion/issue-closer@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Opcional: Adiciona uma label quando fecha automaticamente
          label-name: 'concluido-auto'
